#!/usr/bin/env node

const { spawnSync } = require("child_process");
const { mkdirSync } = require("fs");
const { resolve: resolvePath } = require("path");

// git@github.com:zaverden/esbuild-plugin-postcss.git
const { HOME } = process.env;
const [, , url] = process.argv;
const base = resolvePath(HOME, "dev");

const [, service, ...path] = url.replace(/\.git$/, "").split(/\@|\:|\//);

const repoPath = resolvePath(base, service, ...path);
mkdirSync(repoPath, { recursive: true });
console.log(`repo folder is created: ${repoPath}`);

const gitArgs = ["clone", url, repoPath];
spawnSync("git", gitArgs, {
  stdio: "inherit",
});
